### ISSUE TITLE
Warning should be removed

### ISSUE THREAD

**Issue by marvinbuss** [Azure/arm-deploy#72]
This warning here should be removed from my point of view: https://github.com/Azure/arm-deploy/blob/c241d955ca17a88464fa9d60ce2d0fa3f75375fa/src/deploy/scope_subscription.ts#L12-L15

The warning does not even mention what parameter is affected and lastly this warning is not true. It very much is relevant whether you set the mode to validate or something else. Not sure why this warning is even presented to the user.

You should rather just add a warning that mentions that the mode "Complete" is not supported and therefore it will switch to "Incremental". However, this warning message does not make a whole lot of sense to me.

**Comment by bishal-pdMSFT** [comment]
@marvinbuss this warning essentially is a prompt to user to not use "validate" mode in such a case. User should change the mode to "incremental" and the warning would go away.

**Comment by marvinbuss** [comment]
@bishal-pdMSFT This is not true. If I set the value to `Validate`, the warning is not shown. Just look at the if condition. If I set this to anything else, it starts showing the message. Why are you not creating the same behavior as with the ADO ARM task? This one does not show a warning, if I use the deploymentMode "Incremental".

**Comment by bishal-pdMSFT** [comment]
My bad, I mentioned in the other way round. If deploymentMode is set to anything other than `validate` then it does not have any meaning and it will not have any effect as subscription scope deployment do not support incremental/complete modes.

We could very well not show a warning if deploymentMode is set to incremental or complete, but then it would not be truthful as there is no way to use it. hence we decided to show a warning so that user can fix the input.

**Comment by bishal-pdMSFT** [comment]
Closing this issue. Please re-activate if you still feel this is a problem.
